version: '3.8'

services:
  spark:
    container_name: spark
    build:
      context: ./spark
      dockerfile: Dockerfile
    image: spongres/spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - /tmp:/data
    ports:
      - '8100:8080'

  spark-worker-1:
    image: spongres/spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - /tmp:/data

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    image: spongres/jupyter
    volumes:
      - /tmp:/data
    ports:
      - '9999:8888'
      - '4040:4040'
      - '4041:4041'

  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

