FROM bitnami/spark:3.0.2

RUN curl https://jdbc.postgresql.org/download/postgresql-42.3.3.jar -o /opt/bitnami/spark/jars/postgresql-42.3.3.jar
RUN curl https://repo1.maven.org/maven2/org/mongodb/spark/mongo-spark-connector_2.12/3.0.1/mongo-spark-connector_2.12-3.0.1.jar -o /opt/bitnami/spark/jars/mongo-spark-connector_2.12-3.0.1.jar
